version: "3"
services:
  app:
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:80
    restart: always
  cms:
    build: 
      context: ./cms
      dockerfile: ./Dockerfile
    volumes:
      - ./cms/database:/cms/database
      - ./cms/public:/cms/public
    ports:
      - ${CMS_PORT}:1337
    restart: always
  database:
    image: mysql:8.0.35
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./database/.env
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
    ports:
      - ${DATABASE_PORT}:3306
    restart: always